"""Copy the school data CSVs into schooldata/*.js files so the dashboard can load them.

- School Rollup CSV  -> schooldata/school-data.js   (required)
- school-notes.csv   -> schooldata/school-notes.js  (optional: Renée's visit/update notes)

The CSV text is copied exactly (as one JSON string); nothing is edited.
schooldata/ is git-ignored, so the school data never gets committed.

Notes CSV columns: SchoolNumber, School, Date, Note, Source, Status
(extra columns are kept and shown). Notes connect to schools by SchoolNumber.

Usage:  python dashboard/build-data.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "schooldata"
FILES = [
    (DATA / "Elevate215-School-Data - PHL School Performance Model.xlsx - School Rollup.csv",
     DATA / "school-data.js", "SCHOOL_DATA_CSV", True),
    (DATA / "school-notes.csv", DATA / "school-notes.js", "SCHOOL_NOTES_CSV", False),
]

for csv, out, var, required in FILES:
    if not csv.exists():
        if required:
            raise SystemExit(f"Missing {csv.relative_to(ROOT)}")
        if out.exists():
            out.unlink()  # notes CSV was removed, so disconnect the old copy
        print(f"Skipped {csv.name} (not found)")
        continue
    text = csv.read_bytes().decode("utf-8")  # read raw bytes so line endings stay exactly as in the file
    out.write_text(
        "// Generated by dashboard/build-data.py from:\n"
        f"// {csv.name}\n"
        "// Do not edit by hand. Re-run the script after replacing the CSV.\n"
        f"window.{var} = {json.dumps(text, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    print(f"Wrote {out.relative_to(ROOT)} ({len(text):,} characters from {csv.name})")
